# Generated by Django 5.0.6 on 2024-06-18 06:11

import django.core.validators
import django.db.models.deletion
import smsapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Whitelist_Blacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whitelist_phone', models.TextField()),
                ('blacklist_phone', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='Phone_number_ID',
            field=models.BigIntegerField(default=123456789123456, validators=[smsapp.models.validate_phone_number_id]),
        ),
        migrations.AddField(
            model_name='customuser',
            name='WhatsApp_Business_Account_ID',
            field=models.BigIntegerField(default=123456789123456, validators=[smsapp.models.validate_whatsapp_business_account_id]),
        ),
        migrations.AddField(
            model_name='customuser',
            name='coins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='discount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.CreateModel(
            name='ReportInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_title', models.CharField(max_length=50)),
                ('message_date', models.DateField()),
                ('message_send', models.IntegerField()),
                ('message_delivery', models.IntegerField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
