# Generated by Django 5.0.6 on 2024-07-03 05:40

import smsapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0002_whitelist_blacklist_customuser_phone_number_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='Phone_number_ID',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='WhatsApp_Business_Account_ID',
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number_id',
            field=models.CharField(default=1, max_length=15, validators=[smsapp.models.validate_phone_number_id]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='whatsapp_business_account_id',
            field=models.CharField(default=1, max_length=15, validators=[smsapp.models.validate_whatsapp_business_account_id]),
            preserve_default=False,
        ),
    ]
