# Generated by Django 5.0.6 on 2024-07-04 06:54

import smsapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0003_remove_customuser_phone_number_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportinfo',
            name='message_send',
        ),
        migrations.AddField(
            model_name='reportinfo',
            name='template_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number_id',
            field=models.CharField(default=0, max_length=15, validators=[smsapp.models.validate_phone_number_id]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='whatsapp_business_account_id',
            field=models.CharField(default=0, max_length=15, validators=[smsapp.models.validate_whatsapp_business_account_id]),
        ),
    ]
