# Generated by Django 5.0.6 on 2024-08-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0006_whitelist_blacklist_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportinfo',
            name='contact_list',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
