# Generated by Django 5.0.4 on 2024-04-15 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0008_customuser_coins'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageSendInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_date', models.DateTimeField()),
                ('message_delivery', models.IntegerField()),
                ('message_send', models.IntegerField()),
                ('message_failed', models.IntegerField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
