# Generated by Django 5.0.4 on 2024-04-29 07:39

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0010_composesmsdata_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResellerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('coins', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Reseller User',
                'verbose_name_plural': 'Reseller Users',
            },
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Custom User', 'verbose_name_plural': 'Custom Users'},
        ),
        migrations.AlterField(
            model_name='upload',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif']), django.core.validators.MaxValueValidator(20971520)]),
        ),
        migrations.AlterField(
            model_name='upload',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='uploads/pdfs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), django.core.validators.MaxValueValidator(20971520)]),
        ),
        migrations.AlterField(
            model_name='upload',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='uploads/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'wmv']), django.core.validators.MaxValueValidator(20971520)]),
        ),
        migrations.AlterField(
            model_name='upload',
            name='voice_message',
            field=models.FileField(blank=True, null=True, upload_to='uploads/voice_messages/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg']), django.core.validators.MaxValueValidator(20971520)]),
        ),
    ]
