# Generated by Django 5.0.6 on 2024-10-10 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0010_templatelinkage'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatelinkage',
            name='image_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
