# Generated by Django 5.0.6 on 2024-10-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0011_templatelinkage_image_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledmessage',
            name='submitted_variables',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
