# Generated by Django 5.0.4 on 2024-05-03 11:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0012_customuser_is_reseller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composesmsdata',
            name='email',
        ),
        migrations.RemoveField(
            model_name='messagesendinfo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='email',
        ),
        migrations.RemoveField(
            model_name='whitelist',
            name='email',
        ),
        migrations.CreateModel(
            name='CampaignData',
            fields=[
                ('template_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('sub_service', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=10)),
                ('template_data', models.TextField()),
                ('text', models.FileField(blank=True, null=True, upload_to='uploads/text/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['text']), django.core.validators.MaxValueValidator(5242880)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif']), django.core.validators.MaxValueValidator(3145728)])),
                ('pdf', models.FileField(blank=True, null=True, upload_to='uploads/pdfs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), django.core.validators.MaxValueValidator(5242880)])),
                ('video', models.FileField(blank=True, null=True, upload_to='uploads/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'wmv']), django.core.validators.MaxValueValidator(5242880)])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_date', models.DateTimeField()),
                ('message_delivery', models.IntegerField()),
                ('message_send', models.IntegerField()),
                ('message_failed', models.IntegerField()),
                ('report_file', models.FileField(blank=True, null=True, upload_to='excels/')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Whitelist_Blacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whitelist_phone', models.FileField(upload_to='documents/whitelist/')),
                ('blacklist_phone', models.FileField(upload_to='documents/blacklist/')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Blacklist',
        ),
        migrations.DeleteModel(
            name='ComposeSmsData',
        ),
        migrations.DeleteModel(
            name='MessageSendInfo',
        ),
        migrations.DeleteModel(
            name='Upload',
        ),
        migrations.DeleteModel(
            name='Whitelist',
        ),
    ]
