# Generated by Django 5.0.6 on 2024-11-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0012_scheduledmessage_submitted_variables'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message_type', models.CharField(choices=[('list_message', 'List Message'), ('reply_button_message', 'Reply Button Message'), ('single_product_message', 'Single Product Message'), ('multi_product_message', 'Multi Product Message'), ('send_my_location', 'Send My Location'), ('request_user_location', 'Request User Location'), ('link_template', 'Link Template'), ('send_text_message', 'Send Text Message')], max_length=50)),
                ('user_response', models.CharField(max_length=255)),
                ('body_message', models.TextField()),
                ('sections', models.JSONField(blank=True, default=dict)),
                ('product_section', models.JSONField(blank=True, default=dict)),
                ('catalog_id', models.CharField(blank=True, max_length=255, null=True)),
                ('product_retailer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('template_name', models.CharField(blank=True, max_length=255, null=True)),
                ('buttons', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'message_type'], name='smsapp_mess_user_d5a940_idx'), models.Index(fields=['created_at'], name='smsapp_mess_created_1f360a_idx')],
                'unique_together': {('user', 'user_response')},
            },
        ),
    ]
