# Generated by Django 5.0.4 on 2024-05-04 05:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0013_remove_composesmsdata_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigndata',
            name='voice',
            field=models.FileField(blank=True, null=True, upload_to='uploads/voice/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['voice']), django.core.validators.MaxValueValidator(5242880)]),
        ),
    ]
