# Generated by Django 5.0.4 on 2024-05-04 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0014_campaigndata_voice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigndata',
            name='uploaded_at',
            field=models.DateTimeField(),
        ),
    ]
