# Generated by Django 5.0.4 on 2024-05-04 07:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0015_alter_campaigndata_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportinfo',
            name='original_filename',
            field=models.CharField(default='2024-05-04-07-26-22', max_length=255),
        ),
        migrations.AlterField(
            model_name='campaigndata',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reportinfo',
            name='message_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reportinfo',
            name='report_file',
            field=models.FileField(default=1, upload_to='reports/'),
            preserve_default=False,
        ),
    ]
