# Generated by Django 5.0.4 on 2024-05-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0016_reportinfo_original_filename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportinfo',
            name='original_filename',
            field=models.CharField(default='2024-05-04-07-33-37', max_length=255),
        ),
    ]
