# Generated by Django 5.0.6 on 2024-11-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0017_flows'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='api_token',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
