# Generated by Django 5.0.4 on 2024-05-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0017_alter_reportinfo_original_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportinfo',
            name='original_filename',
            field=models.CharField(default='2024-05-04-08-00-11', max_length=255),
        ),
    ]
