# Generated by Django 5.0.4 on 2024-05-05 18:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0018_alter_reportinfo_original_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigndata',
            name='text',
            field=models.FileField(blank=True, null=True, upload_to='uploads/text/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt']), django.core.validators.MaxValueValidator(5242880)]),
        ),
        migrations.AlterField(
            model_name='reportinfo',
            name='original_filename',
            field=models.CharField(default='2024-05-05-18-06-38', max_length=255),
        ),
    ]
