# Generated by Django 5.0.6 on 2024-11-19 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0018_customuser_api_token_customuser_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_send_msg_to_india', models.BooleanField(default=False)),
                ('can_send_msg_to_nepal', models.BooleanField(default=False)),
                ('can_send_msg_to_us', models.BooleanField(default=False)),
                ('can_send_msg_to_australia', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
