# Generated by Django 5.0.6 on 2024-11-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0019_countrypermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrypermission',
            name='can_send_msg_to_uae',
            field=models.BooleanField(default=False),
        ),
    ]
