# Generated by Django 5.0.4 on 2024-05-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0019_alter_campaigndata_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterModelOptions(
            name='reselleruser',
            options={},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_reseller',
        ),
        migrations.AlterField(
            model_name='reportinfo',
            name='original_filename',
            field=models.CharField(default='2024-05-06-06-30-34', max_length=255),
        ),
    ]
