# Generated by Django 5.0.6 on 2024-11-20 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0020_countrypermission_can_send_msg_to_uae'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotSentMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('phone_number_id', models.CharField(max_length=255)),
                ('contact_list', models.JSONField(blank=True, default=list)),
                ('message_type', models.CharField(choices=[('list_message', 'List Message'), ('reply_button_message', 'Reply Button Message'), ('single_product_message', 'Single Product Message'), ('multi_product_message', 'Multi Product Message'), ('send_my_location', 'Send My Location'), ('request_user_location', 'Request User Location'), ('link_template', 'Link Template'), ('send_text_message', 'Send Text Message')], max_length=50)),
                ('header', models.TextField(blank=True, null=True)),
                ('body', models.TextField()),
                ('footer', models.TextField(blank=True, null=True)),
                ('button_data', models.JSONField(blank=True, default=dict)),
                ('product_data', models.JSONField(blank=True, default=dict)),
                ('catalog_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sections', models.JSONField(blank=True, default=list)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('media_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number_id', 'message_type'], name='smsapp_bots_phone_n_9cefaa_idx'), models.Index(fields=['created_at'], name='smsapp_bots_created_d89079_idx')],
            },
        ),
    ]
