# Generated by Django 5.0.4 on 2024-05-06 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0020_alter_customuser_options_alter_reselleruser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportinfo',
            name='original_filename',
            field=models.CharField(default='2024-05-06-06-32-50', max_length=255),
        ),
    ]
