# Generated by Django 5.0.4 on 2024-05-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0021_alter_reportinfo_original_filename'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResellerUser',
        ),
        migrations.AlterField(
            model_name='reportinfo',
            name='original_filename',
            field=models.CharField(default='2024-05-08-10-47-25', max_length=255),
        ),
    ]
