# Generated by Django 5.0.6 on 2024-11-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0021_botsentmessages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botsentmessages',
            name='button_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='botsentmessages',
            name='contact_list',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='botsentmessages',
            name='product_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='botsentmessages',
            name='sections',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
