# Generated by Django 5.0.6 on 2024-11-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0022_alter_botsentmessages_button_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='authentication_coins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='marketing_coins',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='coins',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
