# Generated by Django 5.0.4 on 2024-05-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0022_delete_reselleruser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='coins',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reportinfo',
            name='original_filename',
            field=models.CharField(default='2024-05-09-09-29-12', max_length=255),
        ),
    ]
