# Generated by Django 5.0.4 on 2024-05-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0023_alter_customuser_coins_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportinfo',
            name='original_filename',
            field=models.CharField(default='2024-05-09-09-32-38', max_length=255),
        ),
    ]
