# Generated by Django 5.0.6 on 2024-12-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0024_train_wit_bot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train_wit_bot',
            name='model_name',
            field=models.CharField(max_length=100),
        ),
    ]
