# Generated by Django 5.0.6 on 2024-05-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0025_alter_customuser_coins_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whitelist_blacklist',
            name='email',
        ),
        migrations.AlterField(
            model_name='reportinfo',
            name='original_filename',
            field=models.CharField(default='2024-05-10-09-37-26', max_length=255),
        ),
    ]
