# Generated by Django 5.0.6 on 2024-12-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0025_alter_train_wit_bot_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccess',
            name='can_access_API_doc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccess',
            name='can_manage_number_validation',
            field=models.BooleanField(default=False),
        ),
    ]
