# Generated by Django 5.0.6 on 2024-05-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0026_remove_whitelist_blacklist_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportinfo',
            name='original_filename',
            field=models.CharField(default='2024-05-10-09-40-10', max_length=255),
        ),
    ]
