# Generated by Django 5.0.6 on 2024-12-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0026_useraccess_can_access_api_doc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register_TwoAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone_number', models.CharField(default=0, max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Validate_TwoAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.CharField(max_length=200)),
                ('otp', models.IntegerField(default=0)),
            ],
        ),
    ]
