# Generated by Django 5.0.6 on 2024-05-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0027_alter_reportinfo_original_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportinfo',
            name='original_filename',
            field=models.CharField(default='2024-05-10-09-42-42', max_length=255),
        ),
    ]
