# Generated by Django 5.0.6 on 2024-12-29 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0027_register_twoauth_validate_twoauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccess',
            name='can_enable_2fauth',
            field=models.BooleanField(default=False),
        ),
    ]
