# Generated by Django 5.0.6 on 2024-05-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0028_alter_reportinfo_original_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportinfo',
            name='original_filename',
            field=models.CharField(default='2024-05-11-09-38-44', max_length=255),
        ),
        migrations.AlterField(
            model_name='reportinfo',
            name='report_file',
            field=models.FileField(null=True, upload_to='reports/'),
        ),
    ]
