# Generated by Django 5.0.6 on 2024-12-31 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0028_useraccess_can_enable_2fauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportinfo',
            name='end_request_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportinfo',
            name='start_request_id',
            field=models.IntegerField(default=0),
        ),
    ]
