# Generated by Django 5.0.6 on 2024-05-15 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0029_alter_reportinfo_original_filename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportinfo',
            name='original_filename',
            field=models.CharField(default='2024-05-15-04-58-56', max_length=255),
        ),
    ]
