# Generated by Django 5.0.6 on 2024-12-31 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0029_reportinfo_end_request_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.CharField(max_length=200)),
                ('campaign_title', models.CharField(default='', max_length=255)),
                ('start_request_id', models.CharField(default=0, max_length=100)),
                ('end_request_id', models.CharField(default=0, max_length=100)),
                ('request_id', models.CharField(max_length=100)),
                ('text', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
