# Generated by Django 5.0.6 on 2025-01-08 09:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0030_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportinfo',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
