# Generated by Django 5.0.6 on 2024-05-15 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0030_alter_reportinfo_original_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportinfo',
            name='original_filename',
            field=models.CharField(default='2024-05-15-05-08-19', max_length=255),
        ),
        migrations.AlterField(
            model_name='whitelist_blacklist',
            name='blacklist_phone',
            field=models.TextField(help_text='+9197453XXXXX'),
        ),
        migrations.AlterField(
            model_name='whitelist_blacklist',
            name='whitelist_phone',
            field=models.TextField(help_text='+9197453XXXXX'),
        ),
    ]
