# Generated by Django 5.0.6 on 2024-05-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0031_alter_reportinfo_original_filename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportinfo',
            name='original_filename',
            field=models.CharField(default='2024-05-15-05-24-31', max_length=255),
        ),
        migrations.AlterField(
            model_name='whitelist_blacklist',
            name='blacklist_phone',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='whitelist_blacklist',
            name='whitelist_phone',
            field=models.TextField(),
        ),
    ]
