# Generated by Django 5.0.6 on 2025-01-24 06:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0032_group_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Last_Replay_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=200)),
                ('last_view', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
