# Generated by Django 5.0.6 on 2024-05-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0034_customuser_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='Discount',
        ),
        migrations.AlterField(
            model_name='reportinfo',
            name='original_filename',
            field=models.CharField(default='2024-05-16-06-28-39', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
