# Generated by Django 5.0.6 on 2025-01-25 08:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0034_remove_last_replay_data_last_view_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='last_replay_data',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
