# Generated by Django 5.0.6 on 2024-05-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0035_remove_customuser_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportinfo',
            name='original_filename',
            field=models.CharField(default='2024-05-16-06-47-37', max_length=255),
        ),
    ]
