# Generated by Django 5.0.6 on 2025-01-27 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0037_customuser_session_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='session_key',
        ),
    ]
