# Generated by Django 5.0.6 on 2024-05-18 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0037_remove_campaigndata_image_remove_campaigndata_pdf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportinfo',
            name='original_filename',
        ),
        migrations.RemoveField(
            model_name='reportinfo',
            name='report_file',
        ),
        migrations.CreateModel(
            name='ReportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_file', models.FileField(null=True, upload_to='reports/')),
                ('original_filename', models.CharField(default='2024-05-18-11-55-11', max_length=255)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
