# Generated by Django 5.0.6 on 2024-05-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0038_remove_reportinfo_original_filename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigndata',
            name='action_type',
            field=models.CharField(choices=[('callToAction', 'Call to Action'), ('visitWebsite', 'Visit Website')], default='hello', max_length=20),
        ),
        migrations.AddField(
            model_name='campaigndata',
            name='button_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaigndata',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='campaigndata',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='coins',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reportfile',
            name='original_filename',
            field=models.CharField(default='2024-05-19-14-01-31', max_length=255),
        ),
    ]
