# Generated by Django 5.0.6 on 2025-01-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0038_remove_customuser_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
