# Generated by Django 5.0.6 on 2025-02-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0039_customuser_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='remarks',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
