# Generated by Django 5.0.6 on 2024-05-21 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0039_campaigndata_action_type_campaigndata_button_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigndata',
            name='campaign_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportfile',
            name='original_filename',
            field=models.CharField(default='2024-05-21-04-18-19', max_length=255),
        ),
    ]
