# Generated by Django 5.0.6 on 2025-02-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0040_customuser_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='user',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='user',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
