# Generated by Django 5.0.6 on 2024-05-21 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0041_alter_reportfile_original_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportfile',
            name='original_filename',
            field=models.CharField(default='2024-05-21-05-03-39', max_length=255),
        ),
    ]
