# Generated by Django 5.0.6 on 2024-05-21 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0042_alter_reportfile_original_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaigndata',
            name='campaign_name',
        ),
        migrations.AddField(
            model_name='reportinfo',
            name='campaign_title',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportfile',
            name='original_filename',
            field=models.CharField(default='2024-05-21-05-51-55', max_length=255),
        ),
    ]
