# Generated by Django 5.0.6 on 2025-02-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0042_scheduledmessage_admin_schedule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_or_email', models.CharField(max_length=255)),
                ('attempt_time', models.DateTimeField(auto_now_add=True)),
                ('is_successful', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('block_until', models.DateTimeField(null=True)),
            ],
        ),
    ]
