# Generated by Django 5.0.6 on 2024-05-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0043_remove_campaigndata_campaign_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportfile',
            name='original_filename',
            field=models.CharField(default='2024-05-28-09-59-35', max_length=255),
        ),
    ]
