# Generated by Django 5.0.6 on 2025-03-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0044_loginhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportinfo',
            name='waba_id_list',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='last_replay_data',
            name='count',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='last_replay_data',
            name='last_count',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='reportinfo',
            name='campaign_title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='reportinfo',
            name='end_request_id',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='reportinfo',
            name='message_delivery',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='reportinfo',
            name='start_request_id',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
