# Generated by Django 5.0.6 on 2025-03-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0045_reportinfo_waba_id_list_alter_last_replay_data_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='whatsapp_business_account_id',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
